### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by vrind-nl** [frankjonen/emacs-for-writers#1]
I personally like [writeroom](https://github.com/joostkremers/writeroom-mode) and [draft-mode](https://github.com/emacsmirror/draft-mode). Any experience with these?

**Comment by frankjonen** [comment]
I hadn't heard of `draft-mode` yet and there isn't really much on its page to see what it does. From the description though it seems to be what I use the `notes.md` buffer for. Really messy thought collection that doesn't yet fit into anything in the main outline. Once a thought is sufficiently drafted out, I add Markdown bits to give the whole thing a modicum of structure. But that's about it.

As for `writeroom` I was initially going for that but then ended up with `Olivetti` instead. One reason was the everything is buffer-local with Olivetti. You'll notice I've set it so only the `org-mode` buffer gets the extra padding, the others don't. I didn't use writeroom much before I switched to Olivetti though. Too many configuration options when all I needed was automatic left/right padding. 

You can switch them out though and see how it goes. Olivetti is only called in line `519` within the org-mode hook. Change it out and see if you prefer the result. Don't forget to load writeroom first though in line `54`.

```lisp
   dotspacemacs-additional-packages '(olivetti)
```
to

```lisp
   dotspacemacs-additional-packages '(writeroom-mode)
```
