### ISSUE TITLE
set window width

### ISSUE THREAD

**Issue by ajreissig** [frankjonen/emacs-for-writers#3]
Hello,
Let me begin to say I love your "emacs for writers" setup.  I especially like the fact that I can open a text window to the right of my org-mode headers.  What I would like is when opening a new window, the old window is only the width of the headings (currently, each window is 50% of my display width).  Is there a way to set this up within the .Spacemacs file?  I have looked through the .Spacemacs file and while I have customized a few things to my liking, I honestly don't know much about elisp and how to configure emacs.
thank you

**Comment by frankjonen** [comment]
Sorry for the late reply. Apparently I don't get issue notifications from Github anymore.

One of the new window layouts in the next update (I'm still writing the new documentation) is what you're looking for. 1/3 headings with 2/3rds for content.

In the meantime you can add `(set-window-width 80)` in a line right after `(find-file "*draft.org" t)` in the `write-window-setup` function. The unit of the `80` part is _columns_ so it's "80 characters of the font you've set" wide. Experiment a little until you like it.
